version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: softhouse.rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
        - '5672:5672'
        - '15672:15672'

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: softhouse.smtp4dev
    restart: always
    ports:
      - '5000:80'
      - '2525:25'

  seq:
    image: datalust/seq:latest
    container_name: softhouse.seq
    ports:
      - "8081:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
  
