version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: softhouse.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 15672:15672

  mailserver:
    image: jijiechen/papercut:latest
    container_name: softhouse.papercut
    ports:
      - 37408:37408
      - 25:25
